name: Accessibility

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pa11y
      - name: Run Pa11y
        run: pa11y https://markj351.github.io/pcHopkinsWebsite/ --threshold 5
